# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeRzSHOeMqCK8nCigbQ4pFniLPoGCJ5D
"""

import numpy as np
import matplotlib.pyplot as plt

# X o'qi uchun qiymatlar
x = np.linspace(0, 2 * np.pi, 1000)  # 0 dan 2π gacha 1000 nuqta

# Sinus funksiyasi
y = np.sin(x)

# Grafigni chizish
plt.figure(figsize=(10, 6))
plt.plot(x, y, label="sin(x)", color="blue")
plt.title("Sinus Grafigi", fontsize=16)
plt.xlabel("x (rad)", fontsize=14)
plt.ylabel("sin(x)", fontsize=14)
plt.axhline(0, color='black', linewidth=0.8, linestyle="--")  # O'x o'qi
plt.axvline(0, color='black', linewidth=0.8, linestyle="--")  # Y o'qi
plt.grid(alpha=0.3)
plt.legend(fontsize=12)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4,5])
y=np.array([0,2,8,1,14,7])
plt.scatter(x,y,color='blue')

x=np.array([12,6,8,11,8,3])
y=np.array([5,6,3,7,17,19])
plt.scatter(x,y,color='blue')
plt.show()